include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - prefer_const_constructors
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - prefer_final_locals
    - require_trailing_commas

formatter:
  trailing_commas: preserve